### ISSUE TITLE
CLI / Pytest plug-in to help add containers to CI config 

### ISSUE THREAD

**Issue by cans** [cans/python-docker-fixtures#16]
Version 0.2.0 adds fixtures compatible with containerized CI environments. But as of now, we do not provide any means to help add the needed containers definitions to such CI environment configuration. This implies some code is duplicated, under the form of python fixtures and under the form of CI configuration.

We also have to stay realistic with respect to the help we can provide. Depending on the freedom the CI system provides, it may be complicated to analyze what is being done in a specific CI task/job and hence determine what container configuration to add to that job.

## Examples

For CircleCI: being able to give the image(s) definition(s) with the right environment variables, commands (and options ?) etc. would be a start.
```
$ docker-fixtures circleci show
```
Would print-out:
```yaml
  - image: some/image:name
    command: ['given', 'command', 'arguments']
    environment:
      GIVEN: environment
      VARIABLES: values
# ...
```

In a later iteration: with the help of mark-up in the CI config be able to auto-update the config. For example:
```yaml
jobs:
  job-name:
    docker:
      - image: primary/image:name
      # BEGIN DOCKER-FIXTURES: <fixture name 1>, ...
      - image: fixture1/image:name
        command: ...
        environment: ...
      # ...
      # END DOCKER-FIXTURES
```
A command like:
```
$ docker-fixtures circleci update
```
Would replace the lines between the marked up blocks with the appropriate container definitions. Note the name of the fixtures given on the `BEGIN` line to help know which images are indeed necessary.

## Potential challenges

- Fixtures can be overwritten how do we deal with that ?
- Fixtures assignment to CI tasks: can we do better than ask for the fixtures names ?
- ...

### Fixtures overwrite ?

First of, can we contextualize well enough when a fixture is used ? (which test ?)

### Fixtures assignement to CI tasks

Use previous tests runs ? Seem brittle and does not help when most needed: when starting up a new project.
